---
title: "PS270 Final Project"
author: "Annie Yu"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to...
the relationship between the likelihood of recidivism and the presence of substance use in WI; still unsure on specifics.  

## Milestone 2

My research question: How does the presence of substance use affect the likelihood of recidivism after incarceration in Wisconsin?

Hypothesis: The presence of substance use increases the likelihood of recidivism in Wisconsin due to the cyclical nature of addiction, isolation/difficulty reengaging with society, lack of rehabilitation treatment centers within jail/prison, and punitive nature of sentencing for drug-related crimes.

The primary explanatory variable is the presence of substance use in an individual's life. This can be measured during the screening and assessment process of intake for correctional facilities, drug testing, self-reported surveys, and medical records. These records alone will show variation among the sample, because those incarcerated now or in the past have different histories with substance use along with varying levels of severity when it comes to disorders. This approach must be longitudinal, because we must see changes or lack of changes in substance use over the span of their life before and during incarceration, along with the three years following their release. That way, we can see at what points in time substance use was at its peak in relation to their criminal behavior. 

The outcome variable of interest is the rate of recidivism for each individual. This is typically measured by the number of re-arrests, re-convictions, and re-incarcerations that occur within three years of being released from jail/prison, including those released on extended supervision/parole. This data is typically public information. 

One observed pattern in the data that would provide support for my hypothesis is higher recidivism rates among those struggling with one or more substance use disorders. 

An observed pattern that would disprove my hypothesis is higher recidivism rates among those without the presence of substance use or those with relatively low levels of substance use. This would mean that substance use is not a causal indicator of high recidivism and that there is a confounding variable that has a larger effect on the likelihood that an individual will re-offend. For instance, mental illness, employment, environment, housing, education, etc. 



